#pragma config(Motor,  motor8, motorL,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,motorR,         tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*                        Copyright (c) James Pearman                          */
/*                                   2014                                      */
/*                            All Rights Reserved                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Module:     clock.c                                                      */
/*    Author:     James Pearman                                                */
/*    Created:    12 April 2014                                                */
/*                                                                             */
/*    Revisions:                                                               */
/*                V1.00     tbd - Initial release                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    The author is supplying this software for use with the VEX IQ            */
/*    control system. This file can be freely distributed and teams are        */
/*    authorized to freely use this program , however, it is requested that    */
/*    improvements or additions be shared with the Vex community via the vex   */
/*    forum.  Please acknowledge the work of the authors when appropriate.     */
/*    Thanks.                                                                  */
/*                                                                             */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/*      http://www.apache.org/licenses/LICENSE-2.0                             */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*                                                                             */
/*    The author can be contacted on the vex forums as jpearman                */
/*    or electronic mail using jbpearman_at_mac_dot_com                        */
/*    Mentor for team 8888 RoboLancers, Pasadena CA.                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/


#include "generic_i2c.c"
#include "matrix.c"
#include "wdMatrixUtil.c"

#define wdMotorFlagLeft     motorL
#define wdMotorFlagRight    motorR

#include "wdMotorLib.c"

// Port for the user sensor that controls the LED matrix
portName userPort;

// Global to hold the time
unsigned long theTime = 0;

// global used to select hours.minutes or seconds
// when setting the time
int     clockSelect = 0;


/*-----------------------------------------------------------------------------*/
// Display clock on LED matrix
void
clockDisplayLed( int secsMarker )
{
    char  str[16];
    int   hours, mins, secs;

    secs  =  theTime % 60;
    mins  = (theTime / 60) % 60;
    hours = (theTime / 3600);

    if( secsMarker )
        sprintf(str,"%02d:%02d", hours, mins );
    else
        sprintf(str,"%02d %02d", hours, mins );

    wdLedCenteredText( userPort, str, );
}

/*-----------------------------------------------------------------------------*/
// Display clock on LCD display

void
clockDisplay()
{
    char  str[16];
    int   hours, mins, secs;
    const int ypos = 36;

    secs  =  theTime % 60;
    mins  = (theTime / 60) % 60;
    hours = (theTime / 3600);

    displayBigStringAt(40, ypos, ":" );
    displayBigStringAt(76, ypos, ":" );

    sprintf(str,"%02d", hours );
    if(clockSelect == 1)
        displayInverseBigStringAt(16, ypos, str );
    else
        displayBigStringAt(16, ypos, str );

    sprintf(str,"%02d", mins );
    if(clockSelect == 2)
        displayInverseBigStringAt(52, ypos, str );
    else
        displayBigStringAt(52, ypos, str );

    sprintf(str,"%02d", secs );
    if(clockSelect == 3)
        displayInverseBigStringAt(88, ypos, str );
    else
        displayBigStringAt(88, ypos, str );
}

/*-----------------------------------------------------------------------------*/
// change hours by given amount
void
clockHoursChange( int value )
{
    int   hours, mins, secs;

    secs  =  theTime % 60;
    mins  = (theTime / 60) % 60;
    hours = (theTime / 3600);

    hours = hours + value;
    if( hours > 23 ) hours -= 24;
    if( hours <  0 ) hours += 24;

    theTime = (hours * 3600) + (mins * 60) + secs;
}
/*-----------------------------------------------------------------------------*/
// change minutes by given amount
void
clockMinsChange( int value )
{
    int   hours, mins, secs;

    secs  =  theTime % 60;
    mins  = (theTime / 60) % 60;
    hours = (theTime / 3600);

    mins = mins + value;
    if( mins > 59 ) mins -= 60;
    if( mins <  0 ) mins += 60;

    theTime = (hours * 3600) + (mins * 60) + secs;
}
/*-----------------------------------------------------------------------------*/
// change seconds by given amount
void
clockSecsChange( int value )
{
    int   hours, mins, secs;

    secs  =  theTime % 60;
    mins  = (theTime / 60) % 60;
    hours = (theTime / 3600);

    secs = secs + value;
    if( secs > 59 ) secs -= 60;
    if( secs <  0 ) secs += 60;

    theTime = (hours * 3600) + (mins * 60) + secs;
}
/*-----------------------------------------------------------------------------*/
// task to update the clock
task
clock()
{
    long lastSysTime;
    int      l, ft;

    while(1)
        {
        // current system time in seconds
        lastSysTime = nSysTime/1000;

        // increase the clock
        theTime++;
        if( theTime == 24*60*60 )
            theTime = 0;

        // Display
        clockDisplay();
        clockDisplayLed(1);

        // wave the hands a little
        if( ft )
            wdMotorFlagOpen(93,87);
        else
            wdMotorFlagOpen(90,90);
        ft = 1 - ft;

        // Now wait 1 second, we could use wait1Msec(1000)
        // but that will probably drift
        l = 0;
        while(lastSysTime == nSysTime/1000)
            {
            wait1Msec(100);

            // part way through turn of the seconds marker
            // on the LED matrix
            if(l++ == 5)
                clockDisplayLed(0);
            }
        }
}

task main()
{
    // Find the user sensor
    userPort = genericI2cFindFirst();

    // We need user sensor LED matrix for this game
    if(userPort < 0)
        {
        eraseDisplay();
        displayBigTextLine( 1, "Sensor");
        displayBigTextLine( 3, "Error");
        while(1) wait1Msec(10);
        }

    // We are initializing, let user know that
    displayTextLine( 1, "Initialize...");

    // Clear the LED matrix
    wdLedClear( userPort );

    // start tasks
    startTask(wdMotorTask);
    wait1Msec(3000);
    wdMotorFlagOpen(90,90);

    eraseDisplay();

    startTask(clock);

    while(1)
        {
        // Use the check button to select hours, minutes or seconds
        // to be set
        if( nLCDButtons == kButtonSelect ) {
            if(++clockSelect == 4)
                clockSelect = 0;
            clockDisplay();
            while( nLCDButtons != kButtonNone )
                wait1Msec(1);
            }

        // Increase button
        if( nLCDButtons == kButtonDown ) {
            switch( clockSelect )
                {
                case    0:  // No action
                    break;
                case    1:
                    clockHoursChange(1);
                    break;
                case    2:
                    clockMinsChange(1);
                    break;
                case    3:
                    clockSecsChange(1);
                    break;
                }
            clockDisplay();
            while( nLCDButtons != kButtonNone )
                wait1Msec(1);
            }

        // Decrease button
        if( nLCDButtons == kButtonUp ) {
            switch( clockSelect )
                {
                case    0:  // No action
                    break;
                case    1:
                    clockHoursChange(-1);
                    break;
                case    2:
                    clockMinsChange(-1);
                    break;
                case    3:
                    clockSecsChange(-1);
                    break;
                }
            clockDisplay();
            while( nLCDButtons != kButtonNone )
                wait1Msec(1);
            }

        wait1Msec(10);
        }
}
