#pragma config(Sensor, port1,  userSensor,     sensorNone)
#pragma config(Sensor, port4,  touch2,         sensorVexIQ_LED)
#pragma config(Sensor, port5,  touch3,         sensorVexIQ_LED)
#pragma config(Sensor, port9,  touch1,         sensorVexIQ_LED)
#pragma config(Sensor, port10, touch4,         sensorVexIQ_LED)
#pragma config(Motor,  motor8, motorL,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,motorR,         tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*                        Copyright (c) James Pearman                          */
/*                                   2014                                      */
/*                            All Rights Reserved                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Module:     matrix_demo.c                                                */
/*    Author:     James Pearman                                                */
/*    Created:    20 June 2014                                                 */
/*                                                                             */
/*    Revisions:                                                               */
/*                V1.00     tbd - Initial release                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    The author is supplying this software for use with the VEX IQ            */
/*    control system. This file can be freely distributed and teams are        */
/*    authorized to freely use this program , however, it is requested that    */
/*    improvements or additions be shared with the Vex community via the vex   */
/*    forum.  Please acknowledge the work of the authors when appropriate.     */
/*    Thanks.                                                                  */
/*                                                                             */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/*      http://www.apache.org/licenses/LICENSE-2.0                             */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*                                                                             */
/*    The author can be contacted on the vex forums as jpearman                */
/*    or electronic mail using jbpearman_at_mac_dot_com                        */
/*    Mentor for team 8888 RoboLancers, Pasadena CA.                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

#include "generic_i2c.c"
#include "matrix.c"
#include "wdMatrixUtil.c"

#define wdMotorFlagLeft     motorL
#define wdMotorFlagRight    motorR

#include "wdMotorLib.c"

// Global for the user sensor port
portName userPort;

/*-----------------------------------------------------------------------------*/
// Run demo on the LED matrix

task
wdMatrixDemo()
{
    // user port shoule have been initialized

    // Clear LED
    wdLedClear( userPort );
    // Wait for motor initialization to finish
    wait1Msec(3000);

    while(1)
        {
        // Open flaps
        wdMotorFlagOpen();

        // close curtain
        wdLedCurtainBitmap( userPort, bitmap_none, false );
        // open to reveal vex
        wdLedCurtainBitmap( userPort, bitmap_vex,  true );
        wait1Msec(1000);
        // Flash vex
        wdLedFlashBitmap( userPort, bitmap_vex, bitmap_none, 5 );
        // Now close
        wdLedCurtainBitmap( userPort, bitmap_vex, false );
        // open to reveal vex iq
        wdLedCurtainBitmap( userPort, bitmap_vexiq,  true );
        wait1Msec(1000);
        // Flash vex
        wdLedFlashBitmap( userPort, bitmap_vexiq, bitmap_none, 5 );
        // Now close
        wdLedCurtainBitmap( userPort, bitmap_vexiq, false );

        // Write some text
        ledMatrixWriteString( userPort, "Vex Robotics   " );
        // and open to text
        wdLedCurtainBitmap( userPort, bitmap_none, true );
        wait1Msec(1000);

        // Scroll to the left
        ledMatrixWriteString( userPort, "Vex Robotics   ", MATRIX_MODE_SPEED_FAST | MATRIX_MODE_SCROLL_LEFT );
        wait1Msec(3000);
        // Scroll to the Right
        ledMatrixWriteString( userPort, "Vex Robotics   ", MATRIX_MODE_SPEED_FAST | MATRIX_MODE_SCROLL_RIGHT );
        wait1Msec(3000);

        // Slow down scrolling now to left
        ledMatrixWriteMode( userPort, MATRIX_MODE_SPEED_SLOW1 | MATRIX_MODE_SCROLL_LEFT );
        wait1Msec(3000);
        // now faster
        ledMatrixWriteMode( userPort, MATRIX_MODE_SPEED_SLOW2 | MATRIX_MODE_SCROLL_LEFT );
        wait1Msec(3000);

        // Flash two bitmaps
        ledMatrixWriteString( userPort, " " );
        wdLedFlashBitmap( userPort, bitmap_128_1, bitmap_128_2, 5 );
        ledMatrixClearBitmap( userPort );

        ledMatrixWriteString( userPort, "Robots      ", (6<<4) | MATRIX_MODE_SCROLL_LEFT );
        wait1Msec(1500);
        wdLedCenteredText( userPort, "are" );
        wait1Msec(1500);
        wdLedCenteredText( userPort, "Fun!" );
        wait1Msec(2000);

        // Done - clear messages
        wdLedCenteredText( userPort, "---" );

        // Close Flags
        wdMotorFlagClose();
        wait1Msec(1000);

        // Clear LED
        wdLedClear( userPort );

        wait1Msec(3000);
        }
}

/*-----------------------------------------------------------------------------*/
// Flash the touch leds

task
wdTouchLedTask()
{
    int  i;

    while(1)
        {
        setTouchLEDRGB( touch1, 255,   0,   0);
        wait1Msec(250);
        setTouchLEDRGB( touch1,   0,   0,   0);
        setTouchLEDRGB( touch2,   0, 255,   0);
        wait1Msec(250);
        setTouchLEDRGB( touch2,   0,   0,   0);
        setTouchLEDRGB( touch3,   0,   0, 255);
        wait1Msec(250);
        setTouchLEDRGB( touch3,   0,   0,   0);
        setTouchLEDRGB( touch4, 255, 255,   0);
        wait1Msec(250);
        setTouchLEDRGB( touch4,   0,   0,   0);
        setTouchLEDRGB( touch3,   0,   0, 255);
        wait1Msec(250);
        setTouchLEDRGB( touch3,   0,   0,   0);
        setTouchLEDRGB( touch2,   0, 255,   0);
        wait1Msec(250);
        setTouchLEDRGB( touch2,   0,   0,   0);
        setTouchLEDRGB( touch1, 255,   0,   0);
        wait1Msec(250);
        setTouchLEDRGB( touch1,   0,   0,   0);

        for(i=0;i<5;i++) {
            setTouchLEDRGB( touch1, 255,   0,   0);
            setTouchLEDRGB( touch2,   0, 255,   0);
            setTouchLEDRGB( touch3,   0,   0, 255);
            setTouchLEDRGB( touch4, 255, 255,   0);
            wait1Msec(250);

            setTouchLEDRGB( touch1,   0,   0,   0);
            setTouchLEDRGB( touch2,   0,   0,   0);
            setTouchLEDRGB( touch3,   0,   0,   0);
            setTouchLEDRGB( touch4,   0,   0,   0);
            wait1Msec(250);
            }
        }
}

#define     LED_TEMP_REG    0x24
#define     LED_SW_REG      0x25
#define     LED_PWM_REG     0x28

task main()
{
    char buffer[4];
    int  i;
    portName userPort;

    // Find the user sensor
    userPort = genericI2cFindFirst();

    // We need user sensor LED matrix for this game
    if(userPort < 0)
        {
        eraseDisplay();
        displayBigTextLine( 1, "Sensor");
        displayBigTextLine( 3, "Error");
        while(1) wait1Msec(10);
        }

    // Clear the LED matrix
    wdLedClear( userPort );

    // Static displays
    drawLine(0, 23, 128, 23);
    displayStringAt(55,33,"Deg C");
    displayStringAt(5,20,"Switch :");
    displayStringAt(5,10,"PWM    :");

    startTask(wdMatrixDemo);
    startTask(wdTouchLedTask);
    startTask(wdMotorTask);

    while(1)
        {
        // Write led brightness
        buffer[0] = i++;
        genericI2cWrite( userPort, LED_PWM_REG, buffer, 1 );

        // Read switch and temperature
        genericI2cRead( userPort, LED_TEMP_REG, buffer, 4 );

        // display temperature
        displayBigStringAt(5, 40, "%3.1f", ((float)buffer[0] / 4 ));

        // display switch status
        if( buffer[1] & 1 )
            displayStringAt(55,20,"Released");
        else
            displayStringAt(55,20,"Pressed ");

        // display current pwm value for the led
        displayStringAt(55,10,"%3d", i & 0xFF);

        wait1Msec(25);
        }
}
